### ISSUE TITLE
Dockerthon dockerfile: missing Xcode:7.0

### ISSUE THREAD

**Issue by arjanclaassen** [jkingyens/dockerthon#1]
Hi, 

I am very interested in setting up our application with an iOS simulator in a docker image. This project looks very promising, also the video. 

While trying it out I cannot find the Xcode:7.0 docker image which is the base the dockerthon docker image.
Can you provide the Xcode:7.0 docker image, or a link to the source?

Thanks

**Comment by jkingyens** [comment]
Hi, thanks for your interest in the project! The xcode:7.0 docker image is not actually a docker image. In this case Xcode:7.0 just tells the build tools to build using xcode 7 on OSX platform. This base "image" is basically the existing development environment on your mac. I wanted to make it look like a traditional dockerfile as much as possible (and match the concepts).

**Comment by ikjot** [comment]
Hi,

How can i link the existing xcode (6.4 in my case) to this dockerfile? 

It shows 
Step 0 : FROM xcode:6.4
Pulling repository xcode
Error: image library/xcode:6.4 not found

**Comment by jkingyens** [comment]
It looks like your docker client is connected to the "real" docker daemon. Did you follow the instructions for starting up the server and pointing your docker client to it?

**Comment by ikjot** [comment]
Yes, i used boot2docker client for running docker on mac. I followed the instructions given on docker official page for mac users. 

I am stuck on the base image in dockerfile for running the xcode project. What is the base image in dockerfile for xcode?

**Comment by jkingyens** [comment]
Sorry, I meant the instructions in this project readme.md. Did you run the following sequence before executing docker commands?

npm install
npm start

and then in a new terminal window type:

export DOCKER_HOST=tcp://localhost:3000
docker ps
docker build
etc

**Comment by karthick9500** [comment]
Same issue here.  (from the osx terminal)

Karthicks-MacBook-Air:docker4xcode karthickv$ docker build -t=test .
Post http:///var/run/docker.sock/v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=test&ulimits=null: dial unix /var/run/docker.sock: no such file or directory.
- Are you trying to connect to a TLS-enabled daemon without TLS?
- Is your docker daemon up and running?
  Karthicks-MacBook-Air:docker4xcode karthickv$ 

**
from docker terminal**

Karthicks-MacBook-Air:docker4xcode karthickv$ docker build -t=test .
Sending build context to Docker daemon 9.052 MB
Step 1 : FROM xcode:7.0
Pulling repository docker.io/library/xcode
Error: image library/xcode not found

**Comment by karthick9500** [comment]
In the new terminal i typed the same as per the procedure 

Karthicks-MacBook-Air:docker4xcode karthickv$ export DOCKER_HOST=tcp://localhost:3000
Karthicks-MacBook-Air:docker4xcode karthickv$ docker ps
Error response from daemon: Cannot GET /v1.20/containers/json
Karthicks-MacBook-Air:docker4xcode karthickv$

**Comment by mattysaw** [comment]
Hi jkingyens, 

Thank you very much for building this awesome repo.
I'm having a similar issue to karthick9500.
Would you have any advice on the matter?
I can detail this more closely if needed.

Thanks,
Mat

**Comment by PrashanthPatil1987** [comment]
Is this a docker command?  HYDRATE

Sending build context to Docker daemon 91.65 kB
Error response from daemon: Unknown instruction: HYDRATE

**Comment by samratBasra** [comment]
Getting below error while running "docker build -t=test ."
Sending build context to Docker daemon 91.65 kB
Error response from daemon: Unknown instruction: HYDRATE

Please help.

**Comment by barrdal** [comment]
Also need help with the HYDRATE command

**Comment by UltraREX** [comment]
+1 Also need help with the Error

Error response from daemon: Dockerfile parse error line 5: unknown instruction: HYDRATE

THX

**Comment by bobbyjey** [comment]
+1 Also need help with the Error

Error response from daemon: Dockerfile parse error line 5: unknown instruction: HYDRATE

I need solution...

**Comment by AhmedHamedTN** [comment]
I am having the same issue here ... 

Error response from daemon: Dockerfile parse error line 5: unknown instruction: HYDRATE

HELP

**Comment by ilkerburak** [comment]
hey @jkingyens do you have any suggestion to resolve Dockerfile parse error line 5: unknown instruction: HYDRATE?
